apiVersion: infra.model/v0alpha1
kind: Network
metadata:
  name: lab-management
spec:
  siteRefs:
    - site/lab-site
  layer: layer2
  prefixes: [192.0.2.0/24]
  defaultGateways:
    - prefix: 192.0.2.0/24
      address: 192.0.2.1
  dns:
    servers:
      - 192.0.2.53
---
apiVersion: infra.model/v0alpha1
kind: Network
metadata:
  name: lab-storage
spec:
  siteRefs:
    - site/lab-site
  layer: layer2
  prefixes: [198.51.100.0/24]
  defaultGateways: []
