apiVersion: infra.model/v0alpha1
kind: Site
metadata:
  name: site-a
spec: {}
---
apiVersion: infra.model/v0alpha1
kind: Site
metadata:
  name: site-b
spec: {}
---
apiVersion: infra.model/v0alpha1
kind: Network
metadata:
  name: multi-site-data
spec:
  layer: layer2
  connectivity: multipoint
  siteRefs:
    - site/site-a
    - site/site-b
---
apiVersion: infra.model/v0alpha1
kind: Cluster
metadata:
  name: multi-site
spec:
  siteRef: site/site-a
  image: {name: Rocky Linux, version: '9'}
  nodes:
    - name: vm-a
      realization: {type: vm}
      requirements:
        compute:
          cpu: {count: 2, unit: vcpu}
        memory:
          capacity: {value: 4, unit: GiB}
        storage:
          capacity: {value: 20, unit: GiB}
      networkAttachments:
        - name: data
          networkRef: network/multi-site-data
          interfaceRequirements: {type: ethernet}
    - name: vm-b
      realization: {type: vm}
      requirements:
        compute:
          cpu: {count: 2, unit: vcpu}
        memory:
          capacity: {value: 4, unit: GiB}
        storage:
          capacity: {value: 20, unit: GiB}
      placement:
        siteRef: site/site-b
      networkAttachments:
        - name: data
          networkRef: network/multi-site-data
          interfaceRequirements: {type: ethernet}
